### ISSUE TITLE
Is this maintained / ready for production?

### ISSUE THREAD

**Issue by fzyzcjy** [MathGaps/d3-force-flutter#3]
Hi thanks for the package! I am refactoring one of my code that uses d3 force directed graph into Flutter and find this package. So I wonder whether this is maintained and ready for production?

**Comment by rlch** [comment]
Hi @fzyzcjy 

It's been tested but I don't have the capacity to maintain this project anymore. I would encourage you to explore whether the project in its current state works for your use-case, or otherwise use JS interop to perform the force calculations.

P.S love your work - seen your many contributions to the Flutter ecosystem 😄

**Comment by fzyzcjy** [comment]
@rlch Hi thanks for the reply, I have tried it and it worked well (for my simple scenario), except that it sometimes yields nan.

> P.S love your work - seen your many contributions to the Flutter ecosystem 😄

Thanks, also happy to see your contributions to Flutter ecosystem!

**Comment by rlch** [comment]
@fzyzcjy As for the NaN case, I believe that should be expected in certain configurations. Have you crossed-check with d3? They might've handled certain edge-cases that produce this behavior imperatively, not sure.

**Comment by fzyzcjy** [comment]
@rlch Not checked yet, since this is not a critical component, and I currently just restart the simulation as a workaround.
